/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as CountriesIndexRouteImport } from './routes/countries.index'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as OrganizationsIdRouteImport } from './routes/organizations.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as CountriesIsoRouteImport } from './routes/countries.$iso'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIdRoute = OrganizationsIdRouteImport.update({
  id: '/organizations/$id',
  path: '/organizations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIsoRoute = CountriesIsoRouteImport.update({
  id: '/countries/$iso',
  path: '/countries/$iso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/facts': typeof FactsRoute
  '/notes': typeof NotesRoute
  '/sources': typeof SourcesRoute
  '/statistics': typeof StatisticsRoute
  '/study': typeof StudyRoute
  '/countries/$iso': typeof CountriesIsoRoute
  '/events/$id': typeof EventsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/countries/': typeof CountriesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/facts': typeof FactsRoute
  '/notes': typeof NotesRoute
  '/sources': typeof SourcesRoute
  '/statistics': typeof StatisticsRoute
  '/study': typeof StudyRoute
  '/countries/$iso': typeof CountriesIsoRoute
  '/events/$id': typeof EventsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/countries': typeof CountriesIndexRoute
  '/events': typeof EventsIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/people': typeof PeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/facts': typeof FactsRoute
  '/notes': typeof NotesRoute
  '/sources': typeof SourcesRoute
  '/statistics': typeof StatisticsRoute
  '/study': typeof StudyRoute
  '/countries/$iso': typeof CountriesIsoRoute
  '/events/$id': typeof EventsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/countries/': typeof CountriesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/facts'
    | '/notes'
    | '/sources'
    | '/statistics'
    | '/study'
    | '/countries/$iso'
    | '/events/$id'
    | '/organizations/$id'
    | '/people/$id'
    | '/countries/'
    | '/events/'
    | '/organizations/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/facts'
    | '/notes'
    | '/sources'
    | '/statistics'
    | '/study'
    | '/countries/$iso'
    | '/events/$id'
    | '/organizations/$id'
    | '/people/$id'
    | '/countries'
    | '/events'
    | '/organizations'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/facts'
    | '/notes'
    | '/sources'
    | '/statistics'
    | '/study'
    | '/countries/$iso'
    | '/events/$id'
    | '/organizations/$id'
    | '/people/$id'
    | '/countries/'
    | '/events/'
    | '/organizations/'
    | '/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FactsRoute: typeof FactsRoute
  NotesRoute: typeof NotesRoute
  SourcesRoute: typeof SourcesRoute
  StatisticsRoute: typeof StatisticsRoute
  StudyRoute: typeof StudyRoute
  CountriesIsoRoute: typeof CountriesIsoRoute
  EventsIdRoute: typeof EventsIdRoute
  OrganizationsIdRoute: typeof OrganizationsIdRoute
  PeopleIdRoute: typeof PeopleIdRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts': {
      id: '/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$id': {
      id: '/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof OrganizationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$iso': {
      id: '/countries/$iso'
      path: '/countries/$iso'
      fullPath: '/countries/$iso'
      preLoaderRoute: typeof CountriesIsoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FactsRoute: FactsRoute,
  NotesRoute: NotesRoute,
  SourcesRoute: SourcesRoute,
  StatisticsRoute: StatisticsRoute,
  StudyRoute: StudyRoute,
  CountriesIsoRoute: CountriesIsoRoute,
  EventsIdRoute: EventsIdRoute,
  OrganizationsIdRoute: OrganizationsIdRoute,
  PeopleIdRoute: PeopleIdRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
