CREATE TYPE public.violence_risk AS ENUM ('low','moderate','high','severe');
ALTER TABLE public.countries ADD COLUMN political_violence_risk public.violence_risk;
INSERT INTO public.countries (name, iso_a3, iso_numeric, flag_emoji, region, subregion, political_violence_risk) VALUES
('Afghanistan','AFG','004','🇦🇫','Asia','Southern Asia','severe'),
('Åland Islands','ALA','248','🇦🇽','Europe','Northern Europe','low'),
('Albania','ALB','008','🇦🇱','Europe','Southern Europe','low'),
('Algeria','DZA','012','🇩🇿','Africa','Northern Africa','moderate'),
('American Samoa','ASM','016','🇦🇸','Oceania','Polynesia','low'),
('Andorra','AND','020','🇦🇩','Europe','Southern Europe','low'),
('Angola','AGO','024','🇦🇴','Africa','Sub-Saharan Africa','moderate'),
('Anguilla','AIA','660','🇦🇮','Americas','Latin America and the Caribbean','low'),
('Antarctica','ATA','010','🇦🇶','Other','','low'),
('Antigua and Barbuda','ATG','028','🇦🇬','Americas','Latin America and the Caribbean','low'),
('Argentina','ARG','032','🇦🇷','Americas','Latin America and the Caribbean','moderate'),
('Armenia','ARM','051','🇦🇲','Asia','Western Asia','moderate'),
('Aruba','ABW','533','🇦🇼','Americas','Latin America and the Caribbean','low'),
('Australia','AUS','036','🇦🇺','Oceania','Australia and New Zealand','low'),
('Austria','AUT','040','🇦🇹','Europe','Western Europe','low'),
('Azerbaijan','AZE','031','🇦🇿','Asia','Western Asia','moderate'),
('Bahamas','BHS','044','🇧🇸','Americas','Latin America and the Caribbean','low'),
('Bahrain','BHR','048','🇧🇭','Asia','Western Asia','moderate'),
('Bangladesh','BGD','050','🇧🇩','Asia','Southern Asia','high'),
('Barbados','BRB','052','🇧🇧','Americas','Latin America and the Caribbean','low'),
('Belarus','BLR','112','🇧🇾','Europe','Eastern Europe','moderate'),
('Belgium','BEL','056','🇧🇪','Europe','Western Europe','low'),
('Belize','BLZ','084','🇧🇿','Americas','Latin America and the Caribbean','moderate'),
('Benin','BEN','204','🇧🇯','Africa','Sub-Saharan Africa','moderate'),
('Bermuda','BMU','060','🇧🇲','Americas','Northern America','low'),
('Bhutan','BTN','064','🇧🇹','Asia','Southern Asia','low'),
('Bolivia, Plurinational State of','BOL','068','🇧🇴','Americas','Latin America and the Caribbean','moderate'),
('Bonaire, Sint Eustatius and Saba','BES','535','🇧🇶','Americas','Latin America and the Caribbean','low'),
('Bosnia and Herzegovina','BIH','070','🇧🇦','Europe','Southern Europe','moderate'),
('Botswana','BWA','072','🇧🇼','Africa','Sub-Saharan Africa','moderate'),
('Bouvet Island','BVT','074','🇧🇻','Americas','Latin America and the Caribbean','low'),
('British Indian Ocean Territory','IOT','086','🇮🇴','Africa','Sub-Saharan Africa','low'),
('Brunei Darussalam','BRN','096','🇧🇳','Asia','South-eastern Asia','low'),
('Bulgaria','BGR','100','🇧🇬','Europe','Eastern Europe','low'),
('Burkina Faso','BFA','854','🇧🇫','Africa','Sub-Saharan Africa','severe'),
('Burundi','BDI','108','🇧🇮','Africa','Sub-Saharan Africa','high'),
('Cabo Verde','CPV','132','🇨🇻','Africa','Sub-Saharan Africa','moderate'),
('Cambodia','KHM','116','🇰🇭','Asia','South-eastern Asia','low'),
('Cameroon','CMR','120','🇨🇲','Africa','Sub-Saharan Africa','high'),
('Canada','CAN','124','🇨🇦','Americas','Northern America','low'),
('Cayman Islands','CYM','136','🇰🇾','Americas','Latin America and the Caribbean','low'),
('Central African Republic','CAF','140','🇨🇫','Africa','Sub-Saharan Africa','high'),
('Chad','TCD','148','🇹🇩','Africa','Sub-Saharan Africa','high'),
('Chile','CHL','152','🇨🇱','Americas','Latin America and the Caribbean','moderate'),
('Christmas Island','CXR','162','🇨🇽','Oceania','Australia and New Zealand','low'),
('Cocos (Keeling) Islands','CCK','166','🇨🇨','Oceania','Australia and New Zealand','low'),
('Colombia','COL','170','🇨🇴','Americas','Latin America and the Caribbean','high'),
('Comoros','COM','174','🇰🇲','Africa','Sub-Saharan Africa','moderate'),
('Congo','COG','178','🇨🇬','Africa','Sub-Saharan Africa','moderate'),
('Congo, Democratic Republic of the','COD','180','🇨🇩','Africa','Sub-Saharan Africa','severe'),
('Cook Islands','COK','184','🇨🇰','Oceania','Polynesia','low'),
('Costa Rica','CRI','188','🇨🇷','Americas','Latin America and the Caribbean','low'),
('Côte d''Ivoire','CIV','384','🇨🇮','Africa','Sub-Saharan Africa','moderate'),
('Croatia','HRV','191','🇭🇷','Europe','Southern Europe','low'),
('Cuba','CUB','192','🇨🇺','Americas','Latin America and the Caribbean','moderate'),
('Curaçao','CUW','531','🇨🇼','Americas','Latin America and the Caribbean','low'),
('Cyprus','CYP','196','🇨🇾','Asia','Western Asia','low'),
('Czechia','CZE','203','🇨🇿','Europe','Eastern Europe','low'),
('Denmark','DNK','208','🇩🇰','Europe','Northern Europe','low'),
('Djibouti','DJI','262','🇩🇯','Africa','Sub-Saharan Africa','moderate'),
('Dominica','DMA','212','🇩🇲','Americas','Latin America and the Caribbean','low'),
('Dominican Republic','DOM','214','🇩🇴','Americas','Latin America and the Caribbean','moderate'),
('Ecuador','ECU','218','🇪🇨','Americas','Latin America and the Caribbean','moderate'),
('El Salvador','SLV','222','🇸🇻','Americas','Latin America and the Caribbean','moderate'),
('Equatorial Guinea','GNQ','226','🇬🇶','Africa','Sub-Saharan Africa','moderate'),
('Eritrea','ERI','232','🇪🇷','Africa','Sub-Saharan Africa','moderate'),
('Estonia','EST','233','🇪🇪','Europe','Northern Europe','low'),
('Eswatini','SWZ','748','🇸🇿','Africa','Sub-Saharan Africa','moderate'),
('Ethiopia','ETH','231','🇪🇹','Africa','Sub-Saharan Africa','high'),
('Falkland Islands (Malvinas)','FLK','238','🇫🇰','Americas','Latin America and the Caribbean','low'),
('Faroe Islands','FRO','234','🇫🇴','Europe','Northern Europe','low'),
('Fiji','FJI','242','🇫🇯','Oceania','Melanesia','moderate'),
('Finland','FIN','246','🇫🇮','Europe','Northern Europe','low'),
('French Guiana','GUF','254','🇬🇫','Americas','Latin America and the Caribbean','low'),
('French Polynesia','PYF','258','🇵🇫','Oceania','Polynesia','low'),
('French Southern Territories','ATF','260','🇹🇫','Africa','Sub-Saharan Africa','low'),
('Gabon','GAB','266','🇬🇦','Africa','Sub-Saharan Africa','moderate'),
('Gambia','GMB','270','🇬🇲','Africa','Sub-Saharan Africa','moderate'),
('Georgia','GEO','268','🇬🇪','Asia','Western Asia','moderate'),
('Ghana','GHA','288','🇬🇭','Africa','Sub-Saharan Africa','moderate'),
('Gibraltar','GIB','292','🇬🇮','Europe','Southern Europe','low'),
('Greece','GRC','300','🇬🇷','Europe','Southern Europe','low'),
('Greenland','GRL','304','🇬🇱','Americas','Northern America','low'),
('Grenada','GRD','308','🇬🇩','Americas','Latin America and the Caribbean','low'),
('Guadeloupe','GLP','312','🇬🇵','Americas','Latin America and the Caribbean','low'),
('Guam','GUM','316','🇬🇺','Oceania','Micronesia','low'),
('Guatemala','GTM','320','🇬🇹','Americas','Latin America and the Caribbean','moderate'),
('Guernsey','GGY','831','🇬🇬','Europe','Northern Europe','low'),
('Guinea','GIN','324','🇬🇳','Africa','Sub-Saharan Africa','moderate'),
('Guinea-Bissau','GNB','624','🇬🇼','Africa','Sub-Saharan Africa','high'),
('Guyana','GUY','328','🇬🇾','Americas','Latin America and the Caribbean','moderate'),
('Haiti','HTI','332','🇭🇹','Americas','Latin America and the Caribbean','severe'),
('Heard Island and McDonald Islands','HMD','334','🇭🇲','Oceania','Australia and New Zealand','low'),
('Holy See','VAT','336','🇻🇦','Europe','Southern Europe','low'),
('Honduras','HND','340','🇭🇳','Americas','Latin America and the Caribbean','high'),
('Hong Kong','HKG','344','🇭🇰','Asia','Eastern Asia','low'),
('Hungary','HUN','348','🇭🇺','Europe','Eastern Europe','low'),
('Iceland','ISL','352','🇮🇸','Europe','Northern Europe','low'),
('Iraq','IRQ','368','🇮🇶','Asia','Western Asia','high'),
('Ireland','IRL','372','🇮🇪','Europe','Northern Europe','low'),
('Isle of Man','IMN','833','🇮🇲','Europe','Northern Europe','low'),
('Italy','ITA','380','🇮🇹','Europe','Southern Europe','low'),
('Jamaica','JAM','388','🇯🇲','Americas','Latin America and the Caribbean','moderate'),
('Jersey','JEY','832','🇯🇪','Europe','Northern Europe','low'),
('Jordan','JOR','400','🇯🇴','Asia','Western Asia','moderate'),
('Kazakhstan','KAZ','398','🇰🇿','Asia','Central Asia','moderate'),
('Kenya','KEN','404','🇰🇪','Africa','Sub-Saharan Africa','high'),
('Kiribati','KIR','296','🇰🇮','Oceania','Micronesia','low'),
('Korea, Democratic People''s Republic of','PRK','408','🇰🇵','Asia','Eastern Asia','moderate'),
('Kuwait','KWT','414','🇰🇼','Asia','Western Asia','moderate'),
('Kyrgyzstan','KGZ','417','🇰🇬','Asia','Central Asia','moderate'),
('Lao People''s Democratic Republic','LAO','418','🇱🇦','Asia','South-eastern Asia','low'),
('Latvia','LVA','428','🇱🇻','Europe','Northern Europe','low'),
('Lebanon','LBN','422','🇱🇧','Asia','Western Asia','high'),
('Lesotho','LSO','426','🇱🇸','Africa','Sub-Saharan Africa','moderate'),
('Liberia','LBR','430','🇱🇷','Africa','Sub-Saharan Africa','moderate'),
('Libya','LBY','434','🇱🇾','Africa','Northern Africa','severe'),
('Liechtenstein','LIE','438','🇱🇮','Europe','Western Europe','low'),
('Lithuania','LTU','440','🇱🇹','Europe','Northern Europe','low'),
('Luxembourg','LUX','442','🇱🇺','Europe','Western Europe','low'),
('Macao','MAC','446','🇲🇴','Asia','Eastern Asia','low'),
('Madagascar','MDG','450','🇲🇬','Africa','Sub-Saharan Africa','moderate'),
('Malawi','MWI','454','🇲🇼','Africa','Sub-Saharan Africa','moderate'),
('Malaysia','MYS','458','🇲🇾','Asia','South-eastern Asia','low'),
('Maldives','MDV','462','🇲🇻','Asia','Southern Asia','low'),
('Mali','MLI','466','🇲🇱','Africa','Sub-Saharan Africa','severe'),
('Malta','MLT','470','🇲🇹','Europe','Southern Europe','low'),
('Marshall Islands','MHL','584','🇲🇭','Oceania','Micronesia','low'),
('Martinique','MTQ','474','🇲🇶','Americas','Latin America and the Caribbean','low'),
('Mauritania','MRT','478','🇲🇷','Africa','Sub-Saharan Africa','moderate'),
('Mauritius','MUS','480','🇲🇺','Africa','Sub-Saharan Africa','moderate'),
('Mayotte','MYT','175','🇾🇹','Africa','Sub-Saharan Africa','low'),
('Micronesia, Federated States of','FSM','583','🇫🇲','Oceania','Micronesia','low'),
('Moldova, Republic of','MDA','498','🇲🇩','Europe','Eastern Europe','moderate'),
('Monaco','MCO','492','🇲🇨','Europe','Western Europe','low'),
('Mongolia','MNG','496','🇲🇳','Asia','Eastern Asia','low'),
('Montenegro','MNE','499','🇲🇪','Europe','Southern Europe','low'),
('Montserrat','MSR','500','🇲🇸','Americas','Latin America and the Caribbean','low'),
('Morocco','MAR','504','🇲🇦','Africa','Northern Africa','moderate'),
('Mozambique','MOZ','508','🇲🇿','Africa','Sub-Saharan Africa','high'),
('Myanmar','MMR','104','🇲🇲','Asia','South-eastern Asia','severe'),
('Namibia','NAM','516','🇳🇦','Africa','Sub-Saharan Africa','moderate'),
('Nauru','NRU','520','🇳🇷','Oceania','Micronesia','low'),
('Nepal','NPL','524','🇳🇵','Asia','Southern Asia','moderate'),
('Netherlands, Kingdom of the','NLD','528','🇳🇱','Europe','Western Europe','low'),
('New Caledonia','NCL','540','🇳🇨','Oceania','Melanesia','low'),
('New Zealand','NZL','554','🇳🇿','Oceania','Australia and New Zealand','low'),
('Nicaragua','NIC','558','🇳🇮','Americas','Latin America and the Caribbean','moderate'),
('Niger','NER','562','🇳🇪','Africa','Sub-Saharan Africa','severe'),
('Niue','NIU','570','🇳🇺','Oceania','Polynesia','low'),
('Norfolk Island','NFK','574','🇳🇫','Oceania','Australia and New Zealand','low'),
('North Macedonia','MKD','807','🇲🇰','Europe','Southern Europe','low'),
('Northern Mariana Islands','MNP','580','🇲🇵','Oceania','Micronesia','low'),
('Norway','NOR','578','🇳🇴','Europe','Northern Europe','low'),
('Oman','OMN','512','🇴🇲','Asia','Western Asia','moderate'),
('Palau','PLW','585','🇵🇼','Oceania','Micronesia','low'),
('Palestine, State of','PSE','275','🇵🇸','Asia','Western Asia','severe'),
('Panama','PAN','591','🇵🇦','Americas','Latin America and the Caribbean','moderate'),
('Papua New Guinea','PNG','598','🇵🇬','Oceania','Melanesia','moderate'),
('Paraguay','PRY','600','🇵🇾','Americas','Latin America and the Caribbean','moderate'),
('Peru','PER','604','🇵🇪','Americas','Latin America and the Caribbean','moderate'),
('Philippines','PHL','608','🇵🇭','Asia','South-eastern Asia','moderate'),
('Pitcairn','PCN','612','🇵🇳','Oceania','Polynesia','low'),
('Portugal','PRT','620','🇵🇹','Europe','Southern Europe','low'),
('Puerto Rico','PRI','630','🇵🇷','Americas','Latin America and the Caribbean','low'),
('Qatar','QAT','634','🇶🇦','Asia','Western Asia','low'),
('Réunion','REU','638','🇷🇪','Africa','Sub-Saharan Africa','low'),
('Romania','ROU','642','🇷🇴','Europe','Eastern Europe','low'),
('Rwanda','RWA','646','🇷🇼','Africa','Sub-Saharan Africa','moderate'),
('Saint Barthélemy','BLM','652','🇧🇱','Americas','Latin America and the Caribbean','low'),
('Saint Helena, Ascension and Tristan da Cunha','SHN','654','🇸🇭','Africa','Sub-Saharan Africa','low'),
('Saint Kitts and Nevis','KNA','659','🇰🇳','Americas','Latin America and the Caribbean','low'),
('Saint Lucia','LCA','662','🇱🇨','Americas','Latin America and the Caribbean','low'),
('Saint Martin (French part)','MAF','663','🇲🇫','Americas','Latin America and the Caribbean','low'),
('Saint Pierre and Miquelon','SPM','666','🇵🇲','Americas','Northern America','low'),
('Saint Vincent and the Grenadines','VCT','670','🇻🇨','Americas','Latin America and the Caribbean','low'),
('Samoa','WSM','882','🇼🇸','Oceania','Polynesia','low'),
('San Marino','SMR','674','🇸🇲','Europe','Southern Europe','low'),
('Sao Tome and Principe','STP','678','🇸🇹','Africa','Sub-Saharan Africa','moderate'),
('Senegal','SEN','686','🇸🇳','Africa','Sub-Saharan Africa','moderate'),
('Seychelles','SYC','690','🇸🇨','Africa','Sub-Saharan Africa','moderate'),
('Sierra Leone','SLE','694','🇸🇱','Africa','Sub-Saharan Africa','moderate'),
('Singapore','SGP','702','🇸🇬','Asia','South-eastern Asia','low'),
('Sint Maarten (Dutch part)','SXM','534','🇸🇽','Americas','Latin America and the Caribbean','low'),
('Slovakia','SVK','703','🇸🇰','Europe','Eastern Europe','low'),
('Slovenia','SVN','705','🇸🇮','Europe','Southern Europe','low'),
('Solomon Islands','SLB','090','🇸🇧','Oceania','Melanesia','moderate'),
('Somalia','SOM','706','🇸🇴','Africa','Sub-Saharan Africa','severe'),
('South Georgia and the South Sandwich Islands','SGS','239','🇬🇸','Americas','Latin America and the Caribbean','low'),
('South Sudan','SSD','728','🇸🇸','Africa','Sub-Saharan Africa','severe'),
('Spain','ESP','724','🇪🇸','Europe','Southern Europe','low'),
('Sri Lanka','LKA','144','🇱🇰','Asia','Southern Asia','moderate'),
('Sudan','SDN','729','🇸🇩','Africa','Northern Africa','severe'),
('Suriname','SUR','740','🇸🇷','Americas','Latin America and the Caribbean','moderate'),
('Svalbard and Jan Mayen','SJM','744','🇸🇯','Europe','Northern Europe','low'),
('Sweden','SWE','752','🇸🇪','Europe','Northern Europe','low'),
('Switzerland','CHE','756','🇨🇭','Europe','Western Europe','low'),
('Syrian Arab Republic','SYR','760','🇸🇾','Asia','Western Asia','severe'),
('Tajikistan','TJK','762','🇹🇯','Asia','Central Asia','moderate'),
('Tanzania, United Republic of','TZA','834','🇹🇿','Africa','Sub-Saharan Africa','moderate'),
('Thailand','THA','764','🇹🇭','Asia','South-eastern Asia','moderate'),
('Timor-Leste','TLS','626','🇹🇱','Asia','South-eastern Asia','low'),
('Togo','TGO','768','🇹🇬','Africa','Sub-Saharan Africa','moderate'),
('Tokelau','TKL','772','🇹🇰','Oceania','Polynesia','low'),
('Tonga','TON','776','🇹🇴','Oceania','Polynesia','low'),
('Trinidad and Tobago','TTO','780','🇹🇹','Americas','Latin America and the Caribbean','moderate'),
('Tunisia','TUN','788','🇹🇳','Africa','Northern Africa','moderate'),
('Turkmenistan','TKM','795','🇹🇲','Asia','Central Asia','moderate'),
('Turks and Caicos Islands','TCA','796','🇹🇨','Americas','Latin America and the Caribbean','low'),
('Tuvalu','TUV','798','🇹🇻','Oceania','Polynesia','low'),
('Uganda','UGA','800','🇺🇬','Africa','Sub-Saharan Africa','moderate'),
('United Arab Emirates','ARE','784','🇦🇪','Asia','Western Asia','moderate'),
('United States Minor Outlying Islands','UMI','581','🇺🇲','Oceania','Micronesia','low'),
('Uruguay','URY','858','🇺🇾','Americas','Latin America and the Caribbean','low'),
('Uzbekistan','UZB','860','🇺🇿','Asia','Central Asia','moderate'),
('Vanuatu','VUT','548','🇻🇺','Oceania','Melanesia','low'),
('Viet Nam','VNM','704','🇻🇳','Asia','South-eastern Asia','low'),
('Virgin Islands (British)','VGB','092','🇻🇬','Americas','Latin America and the Caribbean','low'),
('Virgin Islands (U.S.)','VIR','850','🇻🇮','Americas','Latin America and the Caribbean','low'),
('Wallis and Futuna','WLF','876','🇼🇫','Oceania','Polynesia','low'),
('Western Sahara','ESH','732','🇪🇭','Africa','Northern Africa','low'),
('Yemen','YEM','887','🇾🇪','Asia','Western Asia','severe'),
('Zambia','ZMB','894','🇿🇲','Africa','Sub-Saharan Africa','moderate'),
('Zimbabwe','ZWE','716','🇿🇼','Africa','Sub-Saharan Africa','moderate'),
('Kosovo','XKX','926','🇽🇰','Europe','Southern Europe','moderate');
UPDATE public.countries SET political_violence_risk='moderate' WHERE iso_a3 IN ('BRA','CHN','IND','IDN','SAU','SRB','ZAF');
UPDATE public.countries SET political_violence_risk='low' WHERE iso_a3 IN ('FRA','DEU','JPN','KOR','POL','TWN','GBR','USA');
UPDATE public.countries SET political_violence_risk='high' WHERE iso_a3 IN ('EGY','IRN','MEX','NGA','PAK','TUR','VEN');
UPDATE public.countries SET political_violence_risk='severe' WHERE iso_a3 IN ('ISR','RUS','UKR');